language: go
sudo: required
go:
- 1.13.x
dist: trusty
addons:
  sonarcloud:
    organization: paysuper
stages:
- test
- name: deploy
  if: branch = develop
jobs:
  include:
  - stage: test
    cache:
      directories:
      - $HOME/gopath/pkg/mod  
    install: true
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic -p=1
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
env:
  global:
  - GO111MODULE=on
notifications:
  slack:
    secure: 0haVFs5KtsiB5ZZTLVaLM0DTrMrj20n9auDm/u/P2woJp/Fprigq6U3GSPm6g24Loop7lLijoOHRpIQl1KJH8D8WzcFCNNdmbCRFPKB+EIh56SqiHmql+9MrxlZUkPKZNM7B0f0acSgHP98mISC+grQnhQIGqYaMPXYHS5yTlcLyqbVRBgIdNqTGVVK5+qCakn5f2ht9dseNHCcS5v3xFAXl+w8PQV1oWU03tis5CDTotc0jZRhogknQlyiqTUrLSlawlRLpOVdqh9aGe/NBvx2ZFPiPAp55b1OsmAUrHR8IMpUoGTu2xVdG0/kHldfzXJAG/cT85ZmX1LWs94G3Kszb1HEIGGgWleLtUlsnYF/+ZVlvY1s3WkVCJPsp9AEstduSHp4zsub58jVJIFzXdgcQta8d0/ZEbaU7PbpYyETRkxEN6Pav2P9kBV0M7CfPAO1AFddVtudh3hMk71FE1Jqxp4lCyjhn/DTGkfw9Nxebb4kXKeCGVIgoyO+4eafPDAXjqYDCl+4gbiIH8valt6fO9v2bErAODO4pNwG3ige9+Qpg8xzhzfXaaTTbUniBWj4X1Bbr05vdey5HzblXkZWRARplP7bwpvdzEnRobfraDQ1GlD2OdNBXfXp/RS6lGhcdUtwdqO5RPqsVAkQJXhEF75Hj/K5RJdqt2yMuhDo=
